### PR TITLE
Support using as a class member

### PR DESCRIPTION
**Pull request by ojomio**

### CODE REVIEW

**Comment by JulienPalard** [comment]
Hi! Thanks for your PR, much appreciated!

It's a huge modification, and I like my implementations to be short. Much of your work is toward allowing methods (in any forms) to be used in a Pipe. Do you have a use case for this?

To allow for methods, static methods, and class methods, adding the following is enough:

    def __get__(self, instance, owner):
        return type(self)(self.decorated.__get__(instance, owner))

Maybe explaining in the docstring of our __get__ that we're mimicking the __get__ of functions, and delegating to it to get a bound method.

Two lines would be an acceptable first step, if proved usefull, to allow for Pipe in classes.

**Comment by ojomio** [comment]
OK, you are right, that the else clause is not of much use and `bind` method is only a conveniece.
However, you should definitely inherit from `object` explicitly to allow the descriptor mechanics to work in Python2 and `wrap`ping should be done differently depending on the type of the `decorated` thing (otherwise wrapping fails, for `@staticmethod` doesnt have `__module__`, for example)

**Comment by ojomio** [comment]
As for the usecase - this is pretty obvious. I mean, imaging a http server handler, like Tornado or Flask or any other. It most often is an object with its own methods, and if I incorporate some logic on filtering , sorting and etc of the input data , I would prefer it to be inside that class. But I can't do it with `Pipe` without this patch

**Comment by JulienPalard** [comment]
I don't see why I should wrap differently depending on the type, as long as the __get__ delegates to the original __get__ I'm getting a boud method which know how it has to be called, so the work is done, we don't have to do it.

Tested it like this:

```
from pipe import Pipe, concat

class Foo:
    @Pipe
    def bar(self, iterable):
        for item ∈ iterable:
            yield item ** 2

    @Pipe
    @classmethod
    def baz(cls, iterable):
        for item ∈ iterable:
            yield item ** 2

    @Pipe
    @staticmethod
    def foo(iterable):
        for item ∈ iterable:
            yield item ** 2

print([1, 2, 3] | Foo().bar | Foo.baz | Foo.foo | concat)
# 1, 256, 6561                                                                                                             
```

**Comment by ojomio** [comment]
Look:
```
>>> import functools
>>> def a():
...     print 1
... 
>>> class Foo():
...     @classmethod
...     def bar(cls):
...             print(cls)
...     functools.wraps(bar)(a)
...  
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in Foo
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'classmethod' object has no attribute '__module__'

```

**Comment by ojomio** [comment]
You are right, it does work in my python3.5, because new `wraps()` ignores missing attributes  on a decorated function(`__module__` and `__name__` for `@staticmethod`, for example). 
But it also means not all info is copied, so I'd vote for the options with the most complete information transfer(not to mention that otherwise python2 is not supported)

**Comment by JulienPalard** [comment]
I'll gladly accept, as a first step, as simple two-line PR like just adding:

```
def __get__(self, instance, owner):
    return type(self)(self.decorated.__get__(instance, owner))
```

(with some tests, so OK more than two lines).

We may discuss Python 2 support in another thread, but I may not accept it.

**Comment by JulienPalard** [comment]
I'm going to close this issue out of innactivity, feel free to re-open if you're still interested to work on this. FYI I'm in the process of releasing pipe v2.0 which drops Python 3.6 support, old deprecated pipes, and adds a few features.
